openapi: 3.0.0
info:
  title: Accessibility Report API
  version: 1.0.0
tags:
  - name: Authentication
    description: User authentication and registration
  - name: Reports
    description: Accessibility report submission and retrieval
  - name: Users
    description: User management
  - name: Settings
    description: User settings management
  - name: Admin
    description: Administrative functionalities
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Validation error
        '500':
          description: Internal server error
  /auth/login:
    post:
      summary: Login a user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
        '400':
          description: Validation error
        '500':
          description: Internal server error
  /auth/admin/register:
    post:
      summary: Register a new user (admin only)
      tags:
        - Admin
        - Authentication
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Validation error
        '500':
          description: Internal server error
  /reports:
    post:
      summary: Submit a new accessibility report
      tags:
        - Reports
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                websiteUrl:
                  type: string
                accessibilityScore:
                  type: number
                reportDetails:
                  type: object
      responses:
        '201':
          description: Report submitted successfully
        '400':
          description: Validation error
        '500':
          description: Internal server error
    get:
      summary: Get reports submitted by the authenticated user
      tags:
        - Reports
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of reports
        '500':
          description: Internal server error
  /reports/admin:
    get:
      summary: Get all reports (admin only)
      tags:
        - Admin
        - Reports
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all reports
        '500':
          description: Internal server error
  /reports/public:
    get:
      summary: Get publicly available reports
      tags:
        - Reports
      responses:
        '200':
          description: List of public reports
        '500':
          description: Internal server error
  /reports/flagged:
    get:
      summary: Get flagged reports (moderator/admin only)
      tags:
        - Admin
        - Reports
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of flagged reports
        '500':
          description: Internal server error
  /reports/{id}/flag:
    patch:
      summary: Flag a report (moderator/admin only)
      tags:
        - Admin
        - Reports
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Report flagged successfully
        '500':
          description: Internal server error
  /reports/{id}/unflag:
    patch:
      summary: Unflag a report (admin only)
      tags:
        - Admin
        - Reports
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Report unflagged successfully
        '500':
          description: Internal server error
  /reports/{id}:
    delete:
      summary: Delete a report (admin only)
      tags:
        - Admin
        - Reports
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Report deleted successfully
        '500':
          description: Internal server error
  /users:
    get:
      summary: Get all users (moderator/admin only)
      tags:
        - Admin
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
        '500':
          description: Internal server error
  /users/{id}:
    delete:
      summary: Delete a user (admin only)
      tags:
        - Admin
        - Users
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully
        '500':
          description: Internal server error
  /users/{id}/ban:
    patch:
      summary: Ban a user (moderator/admin only)
      tags:
        - Admin
        - Users
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User banned successfully
        '500':
          description: Internal server error
  /users/{id}/unban:
    patch:
      summary: unban a user (moderator/admin only)
      tags:
        - Admin
        - Users
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User unbanned successfully
        '500':
          description: Internal server error
  /settings:
    patch:
      summary: Update user settings
      tags:
        - Settings
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                darkMode:
                  type: boolean
                language:
                  type: string
      responses:
        '200':
          description: Settings updated successfully
        '400':
          description: Validation error
        '500':
          description: Internal server error
  /settings/password:
    patch:
      summary: Change user password
      tags:
        - Settings
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password changed successfully
        '400':
          description: Validation error
        '500':
          description: Internal server error